version: '3.7'

services:
  bandmates_web:
    container_name: bandmates_web
    build:
      context: .
      dockerfile: Dockerfile_Production
    volumes:
      - '.:/bandmates_web'
      - '/bandmates_web/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true