version: '3.7'

services:
  bandmates_web:
    container_name: bandmates_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true